### ISSUE TITLE
Form not rendering when page is loaded in time not to make screen jump

### ISSUE THREAD

**Issue by arthur-es** [ivan-dalmet/formiz#100]
**Describe the bug**
When you load the page with a multi-step form made with Formizi the screen appears to be "jumping"...most likely beause it takes a few miliseconds to render.

**To Reproduce**
1. Go to https://novo-app-coleta.hyerdev.app/

**Expected behavior**
I expect it not to 'jump'...or if the is no way around it...a way of knowing if its rendering...So I can for example, make use of Skeleton Loading...

**Screenshots**
https://user-images.githubusercontent.com/37699234/140548277-295ef7c9-9069-451a-a841-6f65cb76d43f.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: latest

**Comment by ivan-dalmet** [comment]
Hello @arthur-es thanks for the feedback. I think I've found the global issue behind this. I'm currently working on the fix for this that can also fix #82 
I hope to have time before my first baby 👶 is shipped to production 😅 (it can happen at any time because it's the last month). It can add some delay but I'm working on it 😉

**Comment by ivan-dalmet** [comment]
@arthur-es I think I've found the right solution. Can you test the version `1.8.0-alpha.1` of `@formiz/core` and tell me if it fix your issue?

**Comment by arthur-es** [comment]
> @arthur-es I think I've found the right solution. Can you test the version `1.8.0-alpha.1` of `@formiz/core` and tell me if it fix your issue?

Ivan, it worked! When our project go to prod I'll pay you a coffe :)

**Comment by ivan-dalmet** [comment]
WOW 😍  thanks a lot @arthur-es !
We will drinking a coffee (or a beer :D) knowing that we helped you!

**Comment by ivan-dalmet** [comment]
Version `1.8.0` released with the fix :)
