### ISSUE TITLE
Usefield defaultValue

### ISSUE THREAD

**Issue by Jessy-BAER** [ivan-dalmet/formiz#11]
**Describe the bug**
With react typescript i have a compilation erreur when i try to use `defaultValue` from `useField` hook
 
![image (2)](https://user-images.githubusercontent.com/7570753/72969786-83aa0c80-3dc6-11ea-8729-86a69854a5e2.png)

for now i can fix it with `any`

![image (3)](https://user-images.githubusercontent.com/7570753/72969900-b81dc880-3dc6-11ea-9930-e32b56f812a8.png)

**Comment by ivan-dalmet** [comment]
`useField` don't provide a `defaultValue` property.
If you really need the `defaultValue` you can get it from the component properties.
But in most cases, you don't need to access the `defaultValue`. At init `value` form `useField` will be the `defautlValue` 😉
