### ISSUE TITLE
formiz wizard with React Native

### ISSUE THREAD

**Issue by priscaure** [ivan-dalmet/formiz#15]
Hi, 

I just discovered **Formiz** and I love it. I was just wondering if you had a more complete example on how to use the wizard form with **react native** like this one : [ Wizard ](https://formiz-react.com/docs/demos/wizard)

I understand that we have to put the `as={View}` on the **FormizStep** component but there's so much to add I think, like the form surrounding all the steps with the onSubmit button etc. 

So if you have that on hand that would be awesome ! 
Thank you so much for your help,

Prisca

**Comment by ntorionbearstudio** [comment]
Hi @priscaure ,

Yes you have to put `as={View}` on `FormizStep` component and then create your custom Formiz field component with `useField` hook to be integrated into a Formiz form.

I made a simple demo of Formiz Wizard form with steps in this repository : https://github.com/ntorionbearstudio/formik-react-native-demo

The repository contains a simple React Native app with Formiz for form validations and Native Base for components.

I hope it'll help you

**Comment by priscaure** [comment]
Hi @ntorionbearstudio  ! 

Thank you so so so much for your time and your help, you're a lifesaver :) 

Have a lovely day, 
Prisca
