### ISSUE TITLE
Reset issue on v2 alpha.4

### ISSUE THREAD

**Issue by ivan-dalmet** [ivan-dalmet/formiz#158]
@formiz/core@2.0.0-alpha.4

Reseting a field that will be remove due to the reset (linked field or in a repeater) will mess with initialValues.

https://user-images.githubusercontent.com/9749061/215254377-8a351b8b-3767-4be5-a4f4-c658c27a2227.mov

**Comment by HugoPerard** [comment]
I think this issue can be close ?
