### ISSUE TITLE
Error when submitting step with Enter key press

### ISSUE THREAD

**Issue by cdue** [ivan-dalmet/formiz#2]
When I hit the Enter key in an input field, I expect the form step to be submitted but it's not, and an error is thrown in the console.

How to reproduce:
Go to documentation demo page: Click in the input field, and then press enter. The step is not submitted and an error is thrown in console.

**Comment by ivan-dalmet** [comment]
Just update the lib to v1.0.0-alpha.5. Demo should handle submit when enter is press for steps too :)

**Comment by cdue** [comment]
Perfect, this new version closes the issue :+1:
