### ISSUE TITLE
support rtl 

### ISSUE THREAD

**Issue by izeynali** [ivan-dalmet/formiz#201]
thanks for this tools.
Your plugin supports rtl؟

**Comment by yoannfleurydev** [comment]
Hi @izeynali 

Yes, Formiz is headless, meaning it support any kind of style and any kind of content, including strings with RTL. Formiz is used in 🚀 Start UI [web] https://demo.start-ui.com/app/login , you can try the RTL version by login as an admin and go to the user account to switch the language (🚀 Start UI [web] supports Arabic out of the box).

**Comment by yoannfleurydev** [comment]
I guess it answered your question, I'm closing this issue.
