### ISSUE TITLE
Using localStorage or sessionStorage?

### ISSUE THREAD

**Issue by broeker** [ivan-dalmet/formiz#25]
**Is your feature request related to a problem? Please describe.**
I'm working on a very long multi-step form with many dozens of conditional fields, and so far Formiz is my favorite solution. But I'm hoping to find a way to persist form state on a page refresh.

**Describe the solution you'd like**
I'd like a way to maintain form state in localStorage and/or sessionStorage such that the form survives a page refresh.

**Describe alternatives you've considered**
I've just started considering this and wondering about some approach that would save the entire form.values into local storage, and somehow default to those values if they exist but no idea if this will be possible. 

Any thoughts or is this something you've ever considered? Thank you!

**Comment by ivan-dalmet** [comment]
I think that you can handle this use case with useEffect on form values for saving into localStorage.
And use setFieldsValues (https://formiz-react.com/docs/core/use-form/#setfieldsvaluesobjectofvalues) for getting back the value from the localStorage.
If I have some time on the weekend I will test it and put the code here :)

**Comment by ivan-dalmet** [comment]
If you can share your form values object here, it can be helpful to see the real use case :)

**Comment by ivan-dalmet** [comment]
I've quickly tested. 

I used the [flat package](https://github.com/hughsk/flat) (`npm install flat` or `yarn add flat`) for that example.
This example works well with object syntax like `name="firstname"` or `name="address.city"` but not with array syntax like `name="collection[0].name"` (because the flat package translate arrays to `collection.0.name`).

```jsx
import flatten from 'flat';
/* ... */

const PersistForm = () => {
  const form = useForm();
  const [isLoaded, setIsLoaded] = React.useState(false);

  React.useEffect(() => {
    setTimeout(() => {
      setIsLoaded(true);
      const values = JSON.parse(localStorage.getItem('formValues') || '') || {};
      form.setFieldsValues(flatten(values));
    });
  }, []);

  React.useEffect(() => {
    if (isLoaded) {
      localStorage.setItem('formValues', JSON.stringify(form.values));
    }
  }, [form.values, isLoaded]);

  return null;
};

const MyForm = () => {
  return (
    <Formiz>
      <PersistForm />
      {/* your steps and fields */}
    </Formiz>
  )
}
```

It's not perfect, and I didn't battle-tested the code. But maybe it can help you.

**Comment by broeker** [comment]
@ivan-dalmet this is awesome, thank you. My object syntax follows the "name="address.city"" pattern and I was already using Flat in my submit handler. I haven't had a chance to implement yet but really appreciate the sample code and ideas. 

p.s. I've been evaluating Formik, React Hook Form, Final Form, etc. and while they all have some great pros the simplicity and DX of working with Formiz has been spectacular!

**Comment by broeker** [comment]
Hi again @ivan-dalmet just a note to let you know that I've implemented this on a form with 10+ steps and growing, and so far it is working great. I just hit a use case where I have to use a repeater, and as you noted above your approach doesn't work here due to how Flatten translates the array. 

Any tips on how I might accomodate Repeater fields? So far I'm struggling to come up with a different approach so I thought I might check to see if you have any ideas or can point me in the right direction. 

p.s. I realize your issue queue is not a coding support forum but your original solution above is WAY more elegant than the approaches I was trying so i figure it cannot hurt to ask. Thanks again for the great library :)

**Comment by ivan-dalmet** [comment]
@broeker I think you can transform the myArray.0.myField (from the flatten function) to myArray[0].myField with a regex.

You can try to replace the `form.setFieldsValues(flatten(values));` with the following code (no tested at all ^^)

```js
// ...
const flatValues = Object.entries(values)
  .reduce((obj, [key, value]) => {
    const searchArraySyntax = new RegExp(/(\.)([0-9]+)(\.)?/g)
    const newKey = key.replace(searchArraySyntax, `[$2]$3`)
    return {
      ...obj,
      [newKey]: value,
    }
  }, {});
form.setFieldsValues(flatValues);
// ...
```
(https://playcode.io/632650/)

**Comment by ivan-dalmet** [comment]
@broeker Did it work? 🙂 

Else I think in a next version I will expose the object key/value without parsing. So it will be very easy to do that kind of use case :)

**Comment by broeker** [comment]
Hi @ivan-dalmet sorry for disappearing -- got called away on a different project but I'm back on this one now. 

I have yet to try the code above, but it is on my list and will report back. 

In the meantime, I have hit another related use case, and I'm trying to work out how I can have a dynamic number of form steps. I will post a different ticket.

**Comment by ivan-dalmet** [comment]
@broeker The new version `1.0.0-rc.18` of `@formiz/core` is available with a new option: `form.flatValues` 🎉
Documentation https://formiz-react.com/docs/core/use-form#flatvalues

I think it can help you for your use case :)

**Comment by ivan-dalmet** [comment]
@broeker The new version 1.0.0-rc.22 of @formiz/core is available with a new option: `initialValues` 🎉
See the documentation: https://formiz-react.com/docs/core/formiz#initialvalues
This can be helpful in your use case ;)
