### ISSUE TITLE
SSR id problem

### ISSUE THREAD

**Issue by DecampsRenan** [ivan-dalmet/formiz#26]
Little issue when using NextJS with SSR rendering:

It works as expected, but I still get this error in development only

<img width="646" alt="CleanShot 2020-07-03 at 18 42 36@2x" src="https://user-images.githubusercontent.com/7521065/86486939-0a431c80-bd5d-11ea-94c9-c4f9c33ff4f7.png">

**Comment by ivan-dalmet** [comment]
Thanks for the feedback.

The next version of Formiz will allows you to pass a custom id on the <Formiz> component to get a predictable id on each fields :)

**Comment by ivan-dalmet** [comment]
New version is available 😉

**Comment by DecampsRenan** [comment]
Nice ! I will try 😉
