### ISSUE TITLE
Dynamic number of form steps?

### ISSUE THREAD

**Issue by broeker** [ivan-dalmet/formiz#28]
**Is your feature request related to a problem? Please describe.**
I'm working on an extremely long and complicated governmental form that requires people to input detailed information about each child they have. The number of children is unknown until a user hits that point in the form.

I originally was using a Repeater field but it became overwhelming if a user has something like 8 children (due to the large amount of fieldsx8 on one screen.) I then switched to an accordion based solution by passing the number of children involved from one step to the next; from here I can create one accordion for each child, which works but also also proved to be a bad UX with a large number of children. 

What I am attempting instead is to use one form "step" per child, based on the number of children the user inputs on the previous form step. So for example:

**Step 1:** How many children to you have? (enter number)

**Step 2:** Enter the details for Child 1 (enter many fields)

**Step 3:** Enter the details for Child 2 (enter many fields)

**Step 4:** Continue with rest of form

and so on, where there is an unknown number of children.

**Describe the solution you'd like**

I'm looking for a way that Formiz can adjust to this scenario in a clean way. 

**Describe alternatives you've considered**

I have a work-in-progress but it turns out there are some problems as described below. In the main page of my app I define each step roughly as so:

```
     <MultiStepsLayout
              form={form}
              onValidSubmit={handleSubmit}
              submitLabel="Finish!"
       >
           <PageHeader>My app</PageHeader>
                <InitiateInterview  />
                <BasicInformation />
                <NumberOfChildren />
                <EnterChildren /> --- unknown number of children!
                ...
                <End />
              </>
       </MultiStepsLayout>
```
I pass the number of children to the EnterChildren step, and from there I have a loop like so:

```
      {Array.apply(null, { length: numberChildren }).map((e, index) => (
        <FormizStep key={index} name={`EnterOtherChildren` + index}>
          <SectionWrapper>
            <Box mb="8">
              <SectionHeader
                header={`Enter the details for Child ` + (index + 1) + `:`}
              />
            </Box>
             ...many fields
           </SectionWrapper>
        </FormizStep>
      ))}
```
At first this working just about perfect, until I added any steps AFTER the EnterChildren step. 

In the example above, I have an "End" step (in the real world there will be additional steps). When it is there the app goes first to this End step, and then circles back to the EnterChildren step. 

What I would love to happen is for the total number of "steps" to adjust based on how many children there are, and for the rest of the app to flow from there. 

(Another thing I noticed is that the number to total steps (Step n/n) updates correctly when I select a number of children but if I change that number (say from 4 to 2) it does not adjust accordingly and still  thinks there are two additional steps.)

**Additional context**
I realize I may be pushing this beyond where it was meant to go but I feel like it is very close :)

**Comment by ivan-dalmet** [comment]
Quickly, if you auto generate steps, you will need to pass an `order` on all your `<FormizStep>`

```
<Formiz>
  <FormizStep name="initiateInterview" order={1000} />
  <FormizStep name="basicInformation" order={2000} />
  <FormizStep name="numberOfChildren" order={3000} />
  {array.map((x, index) => (
    <FormizStep name={`enterChildren-${index}`} order={4000 + index} />
  )}
  <FormizStep name="end" order={5000} />
</Formiz>
```

It's not the best code, but it should work ;)

**Comment by ivan-dalmet** [comment]
For the number of steps that didn't change. It's a bug. I will investigate on this when I will have time ;)

**Comment by ivan-dalmet** [comment]
Ok @broeker it seems that there is a bug with dynamic steps that did not update the state. I will try to investigate this on the weekend ;)

**Comment by broeker** [comment]
++++1 

This is awesome and working great. Still have the issue with dynamic steps update so I will keep my eyes out. 

Thank you!

**Comment by ivan-dalmet** [comment]
@broeker New version `1.0.0-rc.15` of `@formiz/core` is available and should fix the issue :)

I've also made a Dynamic Steps example ;)
https://formiz-examples.netlify.app/dynamic-steps
