### ISSUE TITLE
Syncing Fields

### ISSUE THREAD

**Issue by ACampbell12** [ivan-dalmet/formiz#30]
**Is your feature request related to a problem? Please describe.**

First of, I recently found this library, and I love it for so many reasons! So thank you for all the work you put in!

I found myself in a situation where I have a field that I would like to show in two places. I have wrapped Material-UI inputs using `useField()` (see sandbox below) and expected that if I supplied the same *name* property to `useField()` that the forms would stay synced since `useField()` would pull from the same internal state.

For example: 
```
<Formiz connect={form} >
    <CustomField name="syncedField" /> // call this Field1
    <CustomField name="syncedField" /> // call this Field2
</ Formiz>
```

I have found that not to be the case. Both `useField()` calls will alter the same state when `setField` is called, but there is no reactivity. For instance, if *Field1* sets the value to *"test"*, the form state changes but the `value` property returned by `useField()` in *Field2* is not altered. This means that if someone types "a" into *Field2* then the form state is altered to *"a"* but the input of *Field1* remains *"test"*

**Describe the solution you'd like**

All I'm looking for is guidance on best practices to be able to sync fields with each other. Guidance on how to effectively set fields programmatically would be helpful as well (see below).

**Describe alternatives you've considered**

When I came across this, I thought that a solution might be to use `setFieldsValues()` (similar to #18 ) on each change of the field, i.e.
```
<Formiz connect={form} >
    <CustomField name="syncedField" 
        onChange={ (value) => {
            form.setFieldsValues({"syncedField": value)
        } />
    <CustomField name="syncedField"         
        onChange={ (value) => {
            form.setFieldsValues({"syncedField": value)
        } />
</ Formiz>
```

While this does keep the two fields in sync, I'm finding that a side-effect of this is that it clears the other fields (see the Address input in the sandbox below) whenever `setFieldsValues()` is not called. This behavior also confused me a little as I thought `setFieldsValues()` would patch the form, but perhaps that is intended behavior.

Thanks again for this awesome library. Truly a hidden gem!

**Additional context**
[Code Sandbox](https://codesandbox.io/s/great-banach-9yqi0)

**Comment by ivan-dalmet** [comment]
@ACampbell12 
For the 1st case, it's not intended to works.
For the 2nd case, you are right ! The **`setFieldsValues` has a bug** and should patch the form. Give me some time this week to look into it. (on this 2nd case the fact that you have 2 fields with the same name can lead to some issues but the setFieldsValues should work anyway)

**Comment by ivan-dalmet** [comment]
@ACampbell12 Version `1.0.0-rc.16` of `@formiz/core` is available and fix the setFieldsValues issue :)

I've tested in your Code Sandbox with the new version and the 2nd use case works :)

**Comment by ACampbell12** [comment]
Awesome, thank you! 

(Hopefully quick) follow-ups:

- What sort of issues do you foresee with multiple fields of the same name in the same form?
- Are there any other methods that you would recommend for syncing fields like this?

Thanks again!

**Comment by ivan-dalmet** [comment]
> What sort of issues do you foresee with multiple fields of the same name in the same form?

It's not designed with this kind of use case in mind but it should works. Because internally, each fields have a local state and they sync up at global state with a unique id (not the name). The only issue is that the last field with the same name will be the returned value in the `form.values`.

> Are there any other methods that you would recommend for syncing fields like this?

I don't see another way to do that right now. Even on the core, I can't really sync fields by name because of array fields that change names when the user add items in the array (like [this example](https://formiz-examples.netlify.app/repeater))

**Comment by ACampbell12** [comment]
Awesome! Thanks for everything!
