### ISSUE TITLE
Multiple renders

### ISSUE THREAD

**Issue by JordanFAVRE** [ivan-dalmet/formiz#36]
**Describe the bug**
It seems like the forms get rendered multiple times from what I can see in the console ? Why ? Any workaround possible ?

**To Reproduce**
1. Open console log
2. Look at console
3. See 3 renders
4. Question my existence

**Expected behavior**
Only render once or explain why it happens

**Comment by JordanFAVRE** [comment]
Actually I got it wrong, it's fine, I just didn't understand your logging logic.
My bad.
Thanks.

**Comment by ivan-dalmet** [comment]
No problem ^^
