### ISSUE TITLE
**Select only considers when all values are present in available options **A Feature that toggles an input field for user to enter custom option when "other" option is selected

### ISSUE THREAD

**Issue by proxybee** [ivan-dalmet/formiz#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ivan-dalmet** [comment]
Hello @proxybee, I'm not sure to understand your problem.
Can you fill the issue with your problem? :)

**Comment by proxybee** [comment]
**My issue above refers to the select field, in fromiz. what happens when the user's option is not available and the field is required?

**Comment by ivan-dalmet** [comment]
I'm not sure to understand your problem. Can you provide a codesandbox.io or any code example?
