### ISSUE TITLE
Can't access form.values

### ISSUE THREAD

**Issue by KannarFr** [ivan-dalmet/formiz#50]
**Describe the bug**
Using

```javascript
const form = useForm({ subscribe: 'form' });
```

Based on Steppers example, `form.values` is undefined, is that expected behavior? Shouldn't it be accessible for validations as password confirmation?

_Maybe it's all about me and another JS issue because I'm quite bad at it :D._

**Comment by ivan-dalmet** [comment]
@KannarFr Yes subscribing to the "form" only will not give you access to the "fields" values.
This is for performance optimisation. But you can access the values later in the tree.
This is to prevent the root component to rerender on every field change.

Example:
```jsx

const MyFormPart = () => {
  const form = useForm(); // same as useForm({ subscribe: true })
  // Have access to form.values
  return <pre>{JSON.stringify(form?.values, null, 2)}</pre>;
};

const MyForm = () => {
  const form = useForm({ subscribe: 'form' });
  // Don't have access to form.values
  return (
    <Formiz connect={form}>
      <form noValidate onSubmit={form.submit}>
        <MyFormPart />
      </form>
    </Formiz>
  );
};

```

**Comment by KannarFr** [comment]
@ivan-dalmet Oh ok, thanks!
